CREATE TABLE `projects` (
	`slug` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`summary` text NOT NULL,
	`description` text NOT NULL,
	`body` text NOT NULL,
	`role` text NOT NULL,
	`scope` text NOT NULL,
	`status` text NOT NULL,
	`visibility` text NOT NULL,
	`duration` text,
	`team_size` integer,
	`year` integer NOT NULL,
	`github_url` text,
	`live_url` text,
	`image_url` text,
	`technologies` text NOT NULL,
	`outcomes` text,
	`metrics` text,
	`featured_rank` integer,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	CONSTRAINT "status_check" CHECK("projects"."status" IN ('completed', 'in_progress')),
	CONSTRAINT "visibility_check" CHECK("projects"."visibility" IN ('draft', 'published', 'archived'))
);
